# Generated by Django 4.1.7 on 2023-03-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationAPI', '0002_alter_wavescanuser_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wavescanuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member'), ('TECHNICIAN', 'Technician')], max_length=30),
        ),
    ]
