# Generated by Django 4.1.7 on 2023-03-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationAPI', '0003_alter_wavescanuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wavescanuser',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wavescanuser',
            name='designation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
